### PR TITLE
update framework, add SpriteIcon + usages and rework the toolbar to have less constants

### PR DESCRIPTION
**Pull request by jorolf**

### CODE REVIEW

**Comment by apap04** [comment]
rip appveyor

**Comment by apap04** [comment]
yay

**Comment by apap04** [comment]
we should probably merge this to the dev branch

**Comment by apap04** [comment]
so may I edit the pr?

**Comment by apap04** [comment]
rip merge conflicts

**Comment by sr229** [comment]
Thanks rusky, merging this now, just make another PR if you got follow up commits :3

**Pull request merged**
